language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_install:
    - echo "Before install"

before_script:
    - composer self-update
    - composer install

after_script:
    - echo "After script"

notifications:
    webhooks:
        urls:
            - http://bezdomni.net/travis.php
        on_success: always
        on_failure: always
        on_start: true
    irc:
        - "chat.freenode.net#zgphp"
